### ISSUE TITLE
Not an issue - G_ema question

### ISSUE THREAD

**Issue by johndpope** [MontaEllis/DFA-GAN#1]
I have another ticket open on a repo / PTI
https://github.com/danielroich/PTI/issues/26

I don’t know if author can help me / but it seems you’ve crafted the generator / average mean layer / and maybe you can point me in right direction of how to generate this… or not.

Thanks in advance either way

John Pope

**Comment by MontaEllis** [comment]
All the inference codes of stylegan2 are here: https://github.com/MontaEllis/DFA-GAN/blob/master/pytorch_stylegan2/stylegan2_infer_pytorch.py
